### PR TITLE
Add AGPLv3 License

### PR DESCRIPTION
**Pull request by yamanq**
@christopherhafke @benjamincarney @KindaOK @eashwar @siuryan @NoahFiner @alex-gedeon @wiljwang @jacksoncooper Your approval is needed

Licensing our software is an important step in becoming a mature organization. I believe that the AGPLv3 license is the best option for this project. Please see our [meeting notes](https://docs.google.com/presentation/d/1zK38xOiIaG-YE_WRLEEBhm5gFcFmC1T3E60nswZ1694/edit) for details. If you have any questions, feel free to message me on Slack or leave a comment on this pull request.

**Please comment on this pull request to approve this licensing change**. Otherwise, please comment what license you are willing to use, as currently there are no clear terms.

### CODE REVIEW

**Review by KindaOK — APPROVED** [review]
👏👏👏

**Comment by jacksoncooper** [comment]
Hey all I'm no longer a Michigan student. Please feel free to remove me from the OP.

**Comment by yamanq** [comment]
@jacksoncooper This PR is requesting approval from anyone who has committed to this repository, as your approval is needed in order to license the code properly, even if you are no longer contributing to the code base. **Please give your approval to the licensing change** or provide an alternate license under which you would like to release your code committed to this repository.

**Review by jacksoncooper — APPROVED** [review]

**Review by siuryan — APPROVED** [review]

**Comment by benjamincarney** [comment]
Hey Yaman, just saw your email. AGPLv3 license looks good to me!

**Review by eashwar — APPROVED** [review]
sorry for the delay. lgtm!

**Review by christopherhafke — APPROVED** [review]

**Review by wiljwang — APPROVED** [review]

**Review by alex-gedeon — APPROVED** [review]

**Comment by NoahFiner** [comment]
lgtm!

**Review by NoahFiner — APPROVED** [review]
lgtm!

**Comment by yamanq** [comment]
I'll go ahead and merge this then. Thanks everyone!

**Pull request merged**
